---
title: "Assignment 2"
author: "Andrea Lovisolo 19205880"
date: "30/10/2019"
output: pdf_document
---

```{r}
library(readr)
DublinAirport <- read_csv("mly532.csv", skip = 19)
View(DublinAirport)
```

```{r,2}
DublinAirport$month = factor(DublinAirport$month, 1:12, month.name)
```

```{r,3}
Q = aggregate(DublinAirport$rain, by = list(DublinAirport$month),mean)
colnames(Q) = c("Month","Rain")
Q[which.max(Q$Rain),]
Q[which.min(Q$Rain),]

```

```{r,4}
DublinAirport$new.col = factor(DublinAirport$month,month.name,labels = c("Winter","Winter","Spring","Spring","Spring","Summer","Summer","Summer","Autumn","Autumn","Autumn","Winter"),exclude = NULL)
colnames(DublinAirport)[13] = "Seasons"

```

```{r,5}
class(DublinAirport) = c("WeatherData","data.frame")
class(DublinAirport)
```

```{r,6}
summary.WeatherData = function(x) {
  
  
  #RainData
  a = aggregate(x$rain, by = list(x$Seasons),mean)
  colnames(a) = c("Season","Mean(Rain)")
  a2 = aggregate(x$rain, by = list(x$Seasons),sd)
  colnames(a2) = c("Season","Sd(Rain)")
  a3 = aggregate(x$rain, by = list(x$Seasons),min)
  colnames(a3) = c("Season","Min(Rain)")
  a4 = aggregate(x$rain, by = list(x$Seasons),max)
  colnames(a4) = c("Season","Max(Rain)")
  
  a = merge(a,a2)
  a = merge(a,a3)
  a = merge(a,a4)
  
  
  #Mintp data
  
  b= aggregate(x$mintp, by = list(x$Seasons),mean)
  colnames(b) = c("Season","Mean(Mintp)")
  b2= aggregate(x$mintp, by = list(x$Seasons),sd)
  colnames(b2) = c("Season","Sd(Mintp)")
  b3= aggregate(x$mintp, by = list(x$Seasons),min)
  colnames(b3) = c("Season","Min(Mintp)")
  b4= aggregate(x$mintp, by = list(x$Seasons),max)
  colnames(b4) = c("Season","Max(Mintp)")
  
  b = merge(b,b2)
  b = merge(b,b3)
  b = merge(b,b4)
  
  #Maxtp Data
  
  c= aggregate(x$maxtp, by = list(x$Seasons),mean,na.rm = T)
  colnames(c) = c("Season","Mean(Maxtp)")
  c2= aggregate(x$maxtp, by = list(x$Seasons),sd,na.rm = T)
  colnames(c2) = c("Season","Sd(Maxtp)")
  c3= aggregate(x$maxtp, by = list(x$Seasons),min,na.rm = T)
  colnames(c3) = c("Season","Min(Maxtp)")
  c4= aggregate(x$maxtp, by = list(x$Seasons),max,na.rm = T)
  colnames(c4) = c("Season","Max(Maxtp)")
  
  c = merge(c,c2)
  c = merge(c,c3)
  c = merge(c,c4)
  
  #Maxgt Data
  
  d= aggregate(x$maxgt,by = list(x$Seasons),mean,na.rm = T)
  colnames(d) = c("Season","Mean(Maxgt)")
  d2= aggregate(x$maxgt,by = list(x$Seasons),sd,na.rm = T)
  colnames(d2) = c("Season","Sd(Maxgt)")
  d3= aggregate(x$maxgt,by = list(x$Seasons),min,na.rm = T)
  colnames(d3) = c("Season","Min(Maxgt)")
  d4= aggregate(x$maxgt,by = list(x$Seasons),max,na.rm = T)
  colnames(d4) = c("Season","Max(Maxgt)")
  
  d = merge(d,d2)
  d = merge(d,d3)
  d = merge(d,d4)
  
   print(a)
  print(b)
  print(c)
  print(d)
  }

summary(DublinAirport)
 
#DataFrame1 = Every year the dublin airport faces a high average rainfall 
#regardless of the season. 
#The minimum and historical maximum are between 4mm to 200mm 
#with a total everage of 65mm with a variation range of 35mm.

#Dataframe2-3 = The dublin airport historically faces temperatures
#lower than the European average but these do not represent 
#a risk for the circulation of aircraft. 
#Winters face temperatures with average minimum values around -3 degrees
#with and maximums around 2 degrees.
#While the average maximum values during the summer are around 23 degrees.
#Except in special situations therefore the temperature does not represent
#a danger for the circulation of the aircraft.

#Dataframe4 = The power of the gusts is the most critical data for Dublin airport. 
#In every season the airport faces medium gusts of around 45 knots 
#and this can represent a danger for the moving aircraft 
#during take-off and landing.



```


```{r,7, fig.height = 10, fig.width = 10, fig.align = "center"}
plot.WeatherData = function(z, x, y,plot1=T,plot2=T,plot3=T) {
  
  if(missing(x)) {x = 2015}
     if(missing(y)) {y = 2018}
     
  a = x:y

q = z[z$year %in% a,]

par(mfrow = c(1,3))
  
  if (plot1 != FALSE){plot(q$month, q$mintp, col=rgb(1,1,0,1/4), xlab= "Month",ylab= "MinTemp",las = 2)
    
  par(new = TRUE)
  
  plot(q$month, q$maxtp, type = "l", axes = FALSE, bty = "n",xlab= "Month",ylab=NULL,col=rgb(1,0,0,1/4),las = 2)
  axis(side=4, at = pretty(range(q$maxtp)))
  legend("topleft",legend= c("Maxtp = RightValue", "Mintp= LeftValue"),text.col = c(rgb(1,0,0,1/2),rgb(1,1,0,1))) 
 mtext("Maxtemp",4,0.5,cex = 0.8) }  else {plot(NULL)}

nCol = 12


 if (plot2 != FALSE) {plot(q$year,q$rain,type="p",col=rep(1:nCol, each = 12),xlab = "Years",ylab="Rain(Monthly)",main = "AirportData",pch = 19)} else {plot(NULL)}
  
if (plot3 != FALSE) { plot(q$year,q$maxgt,type="p",col=rep(1:nCol, each = 12),xlab="Years",ylab="Maxgt(Monthly)",pch = 19)} else {plot(NULL)}
}

plot(DublinAirport)
```
